# Generated by Django 4.1.6 on 2023-02-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atribuicao',
            options={'ordering': ('atribuicao',), 'verbose_name': 'Atribuição', 'verbose_name_plural': 'Atribuições'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='pessoaatribuicao',
            options={'verbose_name': 'Atribuição da Pessoa', 'verbose_name_plural': 'Atribuições das Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='pessoafisica',
            options={'ordering': ('cpf',), 'verbose_name': 'Pessoa Física', 'verbose_name_plural': 'Pessoas Físicas'},
        ),
        migrations.AlterModelOptions(
            name='pessoajuridica',
            options={'ordering': ('cnpj',), 'verbose_name': 'Pessoa Jurídica', 'verbose_name_plural': 'Pessoas Jurídicas'},
        ),
    ]
