# Generated by Django 4.1.6 on 2023-03-03 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_atribuicao_options_alter_endereco_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoasfisicas', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoasjuridicas', to='pessoas.pessoa'),
        ),
    ]
