# Generated by Django 4.1.6 on 2023-03-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_alter_pessoafisica_pessoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='tipo',
            field=models.CharField(choices=[('J', 'Jurídica'), ('F', 'Física')], db_index=True, default='J', max_length=1),
        ),
    ]
