# Generated by Django 4.1.6 on 2023-07-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_dadospgto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospgto',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pess_conta', to='pessoas.pessoa', verbose_name='Pessoa da conta'),
        ),
        migrations.AlterField(
            model_name='dadospgto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('D', 'CPF/CNPJ'), ('T', 'Celular'), ('E', 'Email'), ('B', 'Agência e Conta'), ('A', 'Chave Aleatória')], default=None, max_length=1, null=True, verbose_name='Tipo da Chave Pix'),
        ),
    ]
