# Generated by Django 4.1.6 on 2023-07-21 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoas', '0007_alter_dadospgto_pessoa_alter_dadospgto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospgto',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização do Movimento'),
        ),
        migrations.AddField(
            model_name='dadospgto',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação do Movimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospgto',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável pelo Movimento'),
        ),
    ]
