# Generated by Django 4.1.6 on 2023-07-24 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoas', '0008_dadospgto_data_atualizacao_dadospgto_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospgto',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização da Conta'),
        ),
        migrations.AlterField(
            model_name='dadospgto',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação da Conta'),
        ),
        migrations.AlterField(
            model_name='dadospgto',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável pela criação da conta'),
        ),
    ]
