# Generated by Django 4.1.6 on 2023-10-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0010_remove_pessoafisica_nacionalidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospgto',
            name='digito_conta',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Digito da Conta'),
        ),
        migrations.AlterField(
            model_name='dadospgto',
            name='numero_conta',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Número da Conta'),
        ),
    ]
