# Generated by Django 4.1.6 on 2023-02-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0002_alter_atribuicao_options_alter_endereco_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição da Espécie do título')),
                ('definitivo', models.BooleanField(default=True, help_text='Marcar falso se tiver caráter provisório. Exemplo: adiantamento.')),
                ('exige_numero', models.BooleanField(default=True, verbose_name='Exige número de documento?')),
                ('exige_arquivo', models.BooleanField(default=False, verbose_name='Exige salvar arquivo digital?')),
                ('observacoes', models.TextField(blank=True, help_text='Notas ou comentários sobre esta espécie', null=True)),
            ],
            options={
                'verbose_name': 'Espécie de Documento',
                'verbose_name_plural': 'Espécies de Documentos',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome ou breve descrição da conta')),
                ('bancaria', models.BooleanField(default=False, verbose_name='É uma conta bancária?')),
                ('numero_banco', models.IntegerField(blank=True, null=True, verbose_name='Número do banco')),
                ('nome_banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do banco')),
                ('numero_agencia', models.SmallIntegerField(blank=True, null=True, verbose_name='Número da agência')),
                ('digito_agencia', models.SmallIntegerField(blank=True, null=True, verbose_name='Dígito da agência')),
                ('numero_conta', models.SmallIntegerField(blank=True, null=True, verbose_name='Número da Conta')),
                ('digito_conta', models.SmallIntegerField(blank=True, null=True, verbose_name='Digito da Conta')),
                ('chave_pix', models.CharField(blank=True, max_length=32, null=True, verbose_name='Chave Pix')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Notas ou comentários sobre esta conta')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.pessoa')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ('nome',),
            },
        ),
    ]
