# Generated by Django 4.1.6 on 2023-02-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0005_centroscustos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Item Orçamentário')),
            ],
            options={
                'verbose_name': 'Item Orçamentário',
                'verbose_name_plural': 'Itens Orçamentários',
                'ordering': ('descricao',),
            },
        ),
    ]
