# Generated by Django 4.1.6 on 2023-02-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0006_itensorcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='definitivo',
            field=models.BooleanField(default=True, help_text='Desmarcar se tiver caráter provisório. Exemplo: adiantamento.'),
        ),
    ]
