# Generated by Django 4.1.6 on 2023-06-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0009_centroscustos_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='exige_arquivo',
            field=models.BooleanField(default=False, verbose_name='Emite recibo?'),
        ),
    ]
