# Generated by Django 4.1.6 on 2023-07-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0010_alter_especie_exige_arquivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contas',
            options={'ordering': ('nome',), 'verbose_name': 'Conta da Adeva', 'verbose_name_plural': 'Contas da Adeva'},
        ),
    ]
