# Generated by Django 4.1.6 on 2023-09-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0011_alter_contas_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contas',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='contas',
            name='favorecido',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do favorecido'),
        ),
    ]
