# Generated by Django 4.1.6 on 2023-09-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0013_contas_cpf_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especie',
            name='definitivo',
        ),
        migrations.RemoveField(
            model_name='especie',
            name='exige_arquivo',
        ),
        migrations.RemoveField(
            model_name='especie',
            name='exige_numero',
        ),
    ]
