# Generated by Django 4.1.6 on 2023-09-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0014_remove_especie_definitivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='numero_conta',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Número da Conta'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='tipo',
            field=models.CharField(choices=[('D', 'Recebiimento'), ('O', 'Pagamento')], default='D', max_length=1),
        ),
    ]
