# Generated by Django 4.1.6 on 2023-02-24 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0006_itensorcamento'),
        ('movimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagarreceber',
            name='item_orcamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lcto_orc', to='configuracoes.itensorcamento', verbose_name='Item Orçamentário'),
            preserve_default=False,
        ),
    ]
