# Generated by Django 4.1.6 on 2023-03-10 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_alter_pessoa_tipo'),
        ('movimentos', '0003_pagarreceber_arquivo_suporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagarreceber',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lcto_pess', to='pessoas.pessoa', verbose_name='Pessoa'),
        ),
    ]
