# Generated by Django 4.1.6 on 2023-06-16 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0009_centroscustos_ativa'),
        ('movimentos', '0004_pagarreceber_pessoa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentoscaixa',
            options={'ordering': ('data_lcto', 'id'), 'verbose_name': 'Movimentação de Caixa', 'verbose_name_plural': 'Movimentações de Caixa'},
        ),
        migrations.AlterField(
            model_name='movimentoscaixa',
            name='conta_destino',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov_conta_destino', to='configuracoes.contas', verbose_name='Conta de Destino'),
        ),
        migrations.AlterField(
            model_name='movimentoscaixa',
            name='conta_origem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov_conta_origem', to='configuracoes.contas', verbose_name='Conta de Origem'),
        ),
        migrations.AlterField(
            model_name='movimentoscaixa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor'),
        ),
    ]
