# Generated by Django 4.1.6 on 2023-06-26 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimentos', '0006_movimentoscaixa_arquivo_suporte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecibosMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rebibo', models.DateField(db_index=True, verbose_name='Data do Recibo')),
                ('emitido', models.BooleanField(blank=True, default=False, null=True, verbose_name='Recibo Emitido')),
                ('lancamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcto_recibo', to='movimentos.pagarreceber', verbose_name='Lançamento de Referência')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'ordering': ('-data_rebibo',),
            },
        ),
        migrations.CreateModel(
            name='ReciboDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('periodo', models.CharField(max_length=80, verbose_name='Período')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recibo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_detalhe', to='movimentos.recibosmaster', verbose_name='Recibo')),
            ],
            options={
                'verbose_name': 'Detalhe do Recibo',
                'verbose_name_plural': 'Detalhes do Recibo',
                'ordering': ('recibo', 'descricao'),
            },
        ),
    ]
