# Generated by Django 4.1.6 on 2023-07-17 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_remove_endereco_municipio_ibge_alter_endereco_uf'),
        ('movimentos', '0009_pagarreceber_codigo_barras_alter_pagarreceber_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPgto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorecido', models.CharField(max_length=100, verbose_name='Nome do favorecido')),
                ('documento', models.CharField(max_length=20, verbose_name='CPF ou CNPJ do favorecido')),
                ('numero_banco', models.IntegerField(blank=True, null=True, verbose_name='Número do banco')),
                ('nome_banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do banco')),
                ('numero_agencia', models.SmallIntegerField(blank=True, null=True, verbose_name='Número da agência')),
                ('digito_agencia', models.SmallIntegerField(blank=True, null=True, verbose_name='Dígito da agência')),
                ('numero_conta', models.SmallIntegerField(blank=True, null=True, verbose_name='Número da Conta')),
                ('digito_conta', models.SmallIntegerField(blank=True, null=True, verbose_name='Digito da Conta')),
                ('tipo', models.CharField(choices=[('D', 'CPF/CNPJ'), ('T', 'Celular'), ('E', 'Email'), ('B', 'Agência e Conta'), ('A', 'Chave Aleatória')], default='D', max_length=1, verbose_name='Tipo da Chave Pix')),
                ('chave_pix', models.CharField(blank=True, max_length=32, null=True, verbose_name='Chave Pix')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Notas ou comentários sobre esta conta')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pess_conta', to='pessoas.pessoa', verbose_name='Pessoa da conta')),
            ],
            options={
                'verbose_name': 'Conta para Pagamento',
                'verbose_name_plural': 'Contas para Pagamentos',
                'ordering': ('favorecido',),
            },
        ),
    ]
