# Generated by Django 4.1.6 on 2023-07-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentos', '0010_dadospgto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosPgto',
        ),
    ]
