# Generated by Django 4.1.6 on 2023-07-21 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimentos', '0012_pagarreceber_conta_pgto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LctoDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição do produto/serviço')),
                ('periodo_qtde', models.CharField(max_length=80, verbose_name='Período/Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lcto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcto_detalhe', to='movimentos.pagarreceber', verbose_name='Recibo')),
            ],
            options={
                'verbose_name': 'Detalhe do Lançamento',
                'verbose_name_plural': 'Detalhes do Lançamento',
                'ordering': ('lcto', 'descricao'),
            },
        ),
    ]
