# Generated by Django 4.1.6 on 2023-07-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentos', '0013_lctodetalhe'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagarreceber',
            name='forma_pgto',
            field=models.CharField(blank=True, choices=[('BL', 'BOLETO'), ('TR', 'TRANSFERÊNCIA'), ('ES', 'ESPÉCIE'), ('OU', 'OUTRO')], default=None, max_length=2, null=True, verbose_name='Status do Pagamento'),
        ),
    ]
