# Generated by Django 4.1.6 on 2023-07-21 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movimentos', '0014_pagarreceber_forma_pgto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagarreceber',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização do Lançamento'),
        ),
        migrations.AddField(
            model_name='pagarreceber',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação do Lançamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagarreceber',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável pelo Lançamento'),
        ),
        migrations.AlterField(
            model_name='pagarreceber',
            name='forma_pgto',
            field=models.CharField(blank=True, choices=[('BL', 'BOLETO'), ('TR', 'TRANSFERÊNCIA'), ('ES', 'ESPÉCIE'), ('OU', 'OUTRO')], default=None, max_length=2, null=True, verbose_name='Forma de Pagamento'),
        ),
    ]
