# Generated by Django 4.1.6 on 2023-07-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimentos', '0016_movimentoscaixa_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibosmaster',
            options={'ordering': ('-data_recibo',), 'verbose_name': 'Recibo', 'verbose_name_plural': 'Recibos'},
        ),
        migrations.RenameField(
            model_name='recibosmaster',
            old_name='data_rebibo',
            new_name='data_recibo',
        ),
        migrations.RemoveField(
            model_name='recibosmaster',
            name='emitido',
        ),
        migrations.RemoveField(
            model_name='recibosmaster',
            name='forma_pagamento',
        ),
        migrations.AlterField(
            model_name='lctodetalhe',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total do item'),
        ),
        migrations.AlterField(
            model_name='recibosmaster',
            name='lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lcto_recibo', to='movimentos.pagarreceber', verbose_name='Lançamento de Referência'),
        ),
        migrations.DeleteModel(
            name='ReciboDetalhe',
        ),
    ]
