# Generated by Django 4.1.6 on 2023-08-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimentos', '0017_alter_recibosmaster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagarreceber',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='documentos', verbose_name='Arquivo a ser carregado'),
        ),
        migrations.AlterField(
            model_name='pagarreceber',
            name='arquivo_suporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcto_arq', to='movimentos.arquivoscontabeis', verbose_name='Arquivo de Suporte Contábil'),
        ),
    ]
