# Generated by Django 4.1.6 on 2023-09-25 14:34

from django.db import migrations, models
import movimentos.models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentos', '0020_delete_arquivoscontabeis_alter_movimentoscaixa_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentoscaixa',
            options={'ordering': ('-data_lcto', 'id'), 'verbose_name': 'Movimentação de Caixa', 'verbose_name_plural': 'Movimentações de Caixa'},
        ),
        migrations.AlterModelOptions(
            name='pagarreceber',
            options={'ordering': ('-data_vcto',), 'verbose_name': 'Conta Pagar/Receber', 'verbose_name_plural': 'Contas a Pagar/Receber'},
        ),
        migrations.AlterField(
            model_name='movimentoscaixa',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=movimentos.models.upload_to_movimentos, verbose_name='Arquivo a ser carregado'),
        ),
        migrations.AlterField(
            model_name='pagarreceber',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=movimentos.models.upload_to_lancamentos, verbose_name='Arquivo a ser carregado'),
        ),
    ]
