# Generated by Django 4.1.6 on 2023-10-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentos', '0021_alter_movimentoscaixa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagarreceber',
            name='forma_pgto',
            field=models.CharField(blank=True, choices=[('BL', 'BOLETO'), ('TR', 'TRANSFERÊNCIA'), ('ES', 'ESPÉCIE'), ('OU', 'OUTRO')], default=None, max_length=2, null=True, verbose_name='Forma de Pagamento(se houver)'),
        ),
    ]
