# Generated by Django 4.1.6 on 2024-02-16 00:40

from django.db import migrations, models
import django.db.models.deletion
import movimentos.models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentos', '0022_alter_pagarreceber_forma_pgto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutrosArquivosLcto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=movimentos.models.upload_to_lancamentos, verbose_name='Arquivo a ser carregado')),
                ('lcto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcto_arquivos', to='movimentos.pagarreceber', verbose_name='Recibo')),
            ],
            options={
                'verbose_name': 'Arquivo do Lançamento',
                'verbose_name_plural': 'Arquivos do Lançamento',
                'ordering': ('lcto',),
            },
        ),
    ]
