# Generated by Django 4.1.6 on 2024-02-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentos', '0023_outrosarquivoslcto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outrosarquivoslcto',
            options={'ordering': ('lcto',), 'verbose_name': 'Arquivo do Lançamento', 'verbose_name_plural': 'Outros Arquivos do Lançamento'},
        ),
    ]
