# Generated by Django 4.1.6 on 2024-02-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0016_descricoeslancamentos_tiposdocumentos'),
        ('movimentos', '0024_alter_outrosarquivoslcto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagarreceber',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lcto_tipo_doc', to='configuracoes.tiposdocumentos', verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='movimentoscaixa',
            name='data_lcto',
            field=models.DateField(db_index=True, verbose_name='Data de Pagamento'),
        ),
    ]
